import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils";
import { Poppins, Inter } from 'next/font/google';


const poppins = Poppins({ subsets: ['latin'], weight: ['400','600','700'], variable: '--font-heading' });
const inter = Inter({ subsets: ['latin'], weight: ['400','500'], variable: '--font-body' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body>
        {children}
      </body>
    </html>
  );
}
